# -*- coding: utf-8 -*-
"""neuroglancer_take_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FLH1kCCu5DSFzFUJUOLBfgSiGbBMywbo

# Neuroglancer on Colab

This notebook explores getting Neuroglancer running on Colab.

[Neuroglancer](https://github.com/google/neuroglancer) is a "WebGL-based viewer for volumetric data" in popular use within the neuroscience community. It is the state of the art. The codebase started inside Google and was open sourced ([Apache License 2.0](https://github.com/google/neuroglancer/blob/master/LICENSE)).

In terms of getting Neuroglancer running on Colab, this might happen in multiple stages.
- An iframe to code and data not on Colab
- Code on Colab. Install neuroglancer on Colab and serve
  - There are Colab specific ways of getting data from server to client
- Generate data on Colab VM and view in Colab UI

For the case of generating data, that target format would be [Neuroglancer precomputed])(https://github.com/google/neuroglancer/tree/master/src/neuroglancer/datasource/precomputed). The generated files could be saved off to... somewhere, say, GitHub (max 100 GB per repo). Optionally, they could just be served up and explored, just to thrown away some hours later.

## Status

As of 2020-02-02, work on this hasn't gone beyond confirming that in *some* fashion Neuroglancer can be embedded into Jupyter notebooks, running on Colab.

## Simple iframe in html magic

The first little piggie's house is just an iframe in and `%%html` magic cell.

Note that this has issues with focus and scrolling which can be reduced simply by zooming the font size down.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <iframe
#       width="600px" height="600px"
#       src="https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B6.000000000000001e-9%2C%22m%22%5D%2C%22y%22:%5B6.000000000000001e-9%2C%22m%22%5D%2C%22z%22:%5B3.0000000000000004e-8%2C%22m%22%5D%7D%2C%22position%22:%5B5523.99072265625%2C8538.9384765625%2C1198.0423583984375%5D%2C%22crossSectionScale%22:3.7621853549999242%2C%22projectionOrientation%22:%5B-0.0040475670248270035%2C-0.9566215872764587%2C-0.22688281536102295%2C-0.18271005153656006%5D%2C%22projectionScale%22:4699.372698097029%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image%22%2C%22name%22:%22original-image%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image_color_corrected%22%2C%22name%22:%22corrected-image%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/ground_truth%22%2C%22selectedAlpha%22:0.63%2C%22notSelectedAlpha%22:0.14%2C%22segments%22:%5B%2213%22%2C%2215%22%2C%222282%22%2C%223189%22%2C%223207%22%2C%223208%22%2C%223224%22%2C%223228%22%2C%223710%22%2C%223758%22%2C%224027%22%2C%22444%22%2C%224651%22%2C%224901%22%2C%224965%22%5D%2C%22name%22:%22ground_truth%22%7D%5D%2C%22layout%22:%224panel%22%7D"
#       />